### PR TITLE
Fix Schema Validation when using DtypeValidator

### PR DESCRIPTION
**Pull request by farridav**
- Fixes dtype validation (`TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'`)
- Fixes existing failing test for validation output
- Adds column name to dtype validation errors if column is passed in
- Some automatic whitepace cleanup by my editor

### CODE REVIEW

**Comment by melvintl** [comment]
+1
Would fix the issue was encountering

**Comment by TMiguelT** [comment]
> Fixes dtype validation
Can you write a test for this point? I assume that's what the `e.row or 0` change was for, but it doesn't look like that test is for that error

> Fixes existing failing test for validation output
Which test was this?

Also I note that you've put your test in `test_schema.py` instead of `test_validation.py`. Can you explain why it's a schema-wide test?

**Comment by farridav** [comment]
@TMiguelT the reason it is a schema unit test is because the error I found was [raised in schema.py](https://github.com/TMiguelT/PandasSchema/pull/18/files#diff-93dc6f979357bf97b205f6ec51377a30R87), and I've made changes to (and assertions for) the output of [validation.py](https://github.com/TMiguelT/PandasSchema/pull/18/files#diff-c584b5c50478034cc974ffa6d98784d6R229)

Perhaps I've labeled the pull request wrong, really its fixing schema validation when using a validator who's `ValidationError` raises do not contain a column, and enriching the respective error messages, I can update PR title to reflect this.

**Comment by TMiguelT** [comment]
As I said above, can you write a test demonstrating the previous error? It would be helpful for me to understand this PR, and to have a test to stop it happening again. You seem to have fixed a bug, but not explained what it is, when it happens, or written tests for it.

> the reason it is a schema unit test is because the error I found was raised in schema.py, and I've made changes to (and assertions for) the output of validation.py

Since you changed the validation message for a specific validator, I think this should go here, in `test_validation.py`: https://github.com/TMiguelT/PandasSchema/blob/master/test/test_validation.py#L466. Your change doesn't affect the entire schema object.

**Comment by TMiguelT** [comment]
To summarise, your PR did 3 things:

* Fixed a `TypeError` bug. This sounds good, but needs a test
* Added the column name to the `IsDtypeValidation` message. This seems reasonable enough, and has a test, but the test is in the wrong place
* Removed whitespace. This is fine
* Fixed `test_example.Example.test_example`, by changing `example.txt` (I think...?). This is also good, I'm not sure how I missed this the first time.

**Comment by kotarf** [comment]
How's this looking? I ran into the same issue with this particular validator.

**Comment by TMiguelT** [comment]
Hi @kotarf, if you're encountering the `TypeError`, could you give me some example code that raises this error? I want this so I can work it in as a test for the library.

**Comment by kotarf** [comment]
> Hi @kotarf, if you're encountering the `TypeError`, could you give me some example code that raises this error? I want this so I can work it in as a test for the library.

I'll need a bit more time to give you a proper test case but my issue is just that the _get_errors_ function for _IsDtypeValidation_ does not return a row # or column name. By not having a row # an uncaught exception is thrown when this validation sees failures and the results are sorted in schema.py:

`        return sorted(errors, key=lambda e: e.row)
`

**Comment by TMiguelT** [comment]
Ohh, that's finally explained this PR to me. I didn't realise the two errors @farridav claimed to fix were actually the same. In that case, all I need to do is move the test already present to the right place and this PR should be fine. You won't need to write your own test case @kotarf, because this PR already has one.

**Comment by TMiguelT** [comment]
@farridav, is there a chance you can enable PR editing so I can let you keep attribution but I can tweak some things?

**Comment by farridav** [comment]
Sure, I've added you as a collaborator, check your invites

**Comment by TMiguelT** [comment]
Oh, I just meant PR editing: https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by farridav** [comment]
Sure, that box appears to already be ticked

**Comment by TMiguelT** [comment]
Okay I've edited this PR by:
* I made the default `ValidationWarning` row number -1, so that warnings without rows (e.g. the `Dtype` warning discussed here) won't have any issues. This is a slightly different solution to the original PR, but I think it's a bit nicer
* Moved the new test to the validation tests file
* Undid an attempted fix to the example file that was already fixed by #20. I know this PR came first, but I preferred the fix in #20 because it meant producing more user-friendly messages

**Pull request merged**
