### PR TITLE
support category dtypes

### LINKED ISSUE #22: get_errors() fails when Series.dtype=category
`if np.issubdtype(series.dtype, np.number):`  from https://github.com/TMiguelT/PandasSchema/blob/c157e1423188d9bd82d7f268128eda67acd2d4f4/pandas_schema/validation.py#L87-L90 fails for pandas dtype of category with error `TypeError: data type not understood`. I'll open a PR shortly to better handle this dtype checking. Thinking something simple like 

            try:
                if np.issubdtype(series.dtype, np.number):
                    validated = ~series.isna() & simple_validation
                else:
                    validated = (series.str.len() > 0) & simple_validation
            except TypeError as te:
                validated = (series.str.len() > 0) & simple_validation

### PR DESCRIPTION
**Pull request by caddac**
Resolves #22

### CODE REVIEW

**Comment by TMiguelT** [comment]
Hi David, thanks for identifying and fixing this issue. I have two suggestions on how I'd like this implemented.

Firstly, it seems that the more elegant way to do this broad type checking is with the `pandas.api.types` functions, as explained here: https://stackoverflow.com/a/38185759/2148718. These seem to have existed since 0.19 (2016), so I'm happy to bump the pandas version requirement and use them. This would, for example, give us access to [`pandas.api.types.is_categorical_dtype`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.api.types.is_categorical_dtype.html#pandas.api.types.is_categorical_dtype). This would also stop pandas throwing an error if you try to check a categorical column, and instead it would just return false, which is ideal.

Secondly, I think we could improve your actual skip-empty behaviour for categoricals: 
```python
validated = (series.astype(object).str.len() > 0) & simple_validation
```
Currently you're converting the axis to a string and checking for empty strings, but I don't believe this is the idiomatic way to treat categoricals. In theory the user might actually have the empty string as one of their categories, and so we don't want to ignore a column in this case. On the other hand, the [documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html) says "All values of categorical data are either in categories or np.nan", which makes me think that, like with numericals, we should treat only `np.nan` as an empty categorical column.

**Comment by caddac** [comment]
Allright, I think I've got this all wrapped up now. Ended up having to use pandas>=0.21 for the `Series.isna()` call which failed on pandas 0.19.

**Comment by caddac** [comment]
OK, I think I've got this all wrapped up. Ended up going with pandas version 21.0 because its required for the `series.isna()` call. I did install pandas 0.21 and all the tests pass, but not with 0.19.

**Comment by TMiguelT** [comment]
Hmm, unless I use that method elsewhere, you might as well change it to `isnull()` (https://pandas.pydata.org/pandas-docs/version/0.19/generated/pandas.Series.isnull.html#pandas.Series.isnull), just so we can support the most versions of pandas possible.

**Comment by caddac** [comment]
OK, working with pandas 0.19!

**Comment by caddac** [comment]
For some reason the comments on this PR are completely out of order, I've submitted a ticket to Github. Very confusing...

**Comment by TMiguelT** [comment]
Excellent, looks good! I tweaked some of your docstrings, but nothing major.

> For some reason the comments on this PR are completely out of order, I've submitted a ticket to Github. Very confusing...

Yep I also noticed that. Never seen it before...

**Comment by TMiguelT** [comment]
This is now available as a GitHub release and on PyPi as 0.3.4

**Pull request merged**
